# Assemble subset .h5ad files

For QC and inspection of our cell type labels, we'll assemble samples based on subject metadata to get some reusable units that will be manageable for downstream analysis. 

To each of these subsets, we'll add our cell type label predictions and scrublet scores and calls.

We'll carry these subsets forward into QC filtering and cell type-based doublet and mislabeling clean-up in later notebooks.

## Load Packages

`anndata`: Data structures for scRNA-seq  
`datetime`: date and time functions  
`h5py`: HDF5 file I/O  
`hisepy`: The HISE SDK for Python  
`os`: operating system calls  
`pandas`: DataFrame data structures  
`re`: Regular expressions  
`scanpy`: scRNA-seq analysis  
`scipy.sparse`: Spare matrix data structures

In [21]:
import anndata
from datetime import date
import h5py
import hisepy
import os
import pandas as pd
from pandas.api.types import is_object_dtype
import re
import scanpy as sc
import scipy.sparse as scs
import numpy as np

## Helper functions

In [2]:
def cache_uuid_path(uuid):
    cache_path = '/home/jupyter/cache/{u}'.format(u = uuid)
    if not os.path.isdir(cache_path):
        hise_res = hisepy.reader.cache_files([uuid])
    filename = os.listdir(cache_path)[0]
    cache_file = '{p}/{f}'.format(p = cache_path, f = filename)
    return cache_file

In [53]:
hisepy.__version__

'0.3.0'

In [3]:
def read_csv_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = pd.read_csv(cache_file)
    return res

In [4]:
def read_parquet_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = pd.read_parquet(cache_file)
    return res

Functions to read pipeline .h5 files as anndata

In [5]:
# define a function to read count data
def read_mat(h5_con):
    mat = scs.csc_matrix(
        (h5_con['matrix']['data'][:], # Count values
         h5_con['matrix']['indices'][:], # Row indices
         h5_con['matrix']['indptr'][:]), # Pointers for column positions
        shape = tuple(h5_con['matrix']['shape'][:]) # Matrix dimensions
    )
    return mat

# define a function to read obeservation metadata (i.e. cell metadata)
def read_obs(h5con):
    bc = h5con['matrix']['barcodes'][:]
    bc = [x.decode('UTF-8') for x in bc]

    # Initialized the DataFrame with cell barcodes
    obs_df = pd.DataFrame({ 'barcodes' : bc })

    # Get the list of available metadata columns
    obs_columns = h5con['matrix']['observations'].keys()
    
    # For each column
    for col in obs_columns:
        # Read the values
        values = h5con['matrix']['observations'][col][:]
        # Check for byte storage
        if(isinstance(values[0], (bytes, bytearray))):
            # Decode byte strings
            values = [x.decode('UTF-8') for x in values]
        # Add column to the DataFrame
        obs_df[col] = values

    obs_df = obs_df.set_index('barcodes', drop = False)
    
    return obs_df

# define a function to construct anndata object from a h5 file
def read_h5_anndata(h5_file):
    h5_con = h5py.File(h5_file, mode = 'r')
    # extract the expression matrix
    mat = read_mat(h5_con)
    # extract gene names
    genes = h5_con['matrix']['features']['name'][:]
    genes = [x.decode('UTF-8') for x in genes]
    # extract metadata
    obs_df = read_obs(h5_con)
    # construct anndata
    adata = anndata.AnnData(mat.T,
                             obs = obs_df)
    # make sure the gene names aligned
    adata.var_names = genes

    adata.var_names_make_unique()
    return adata

In [6]:
def element_id(n = 3):
    import periodictable
    from random import randrange
    rand_el = []
    for i in range(n):
        el = randrange(0,118)
        rand_el.append(periodictable.elements[el].name)
    rand_str = '-'.join(rand_el)
    return rand_str

## Read sample metadata from HISE

In [7]:
in_uuids = []

In [8]:
## sample_meta_uuid from previous step
sample_meta_uuid = '2b3673ee-827b-415e-837b-f27a0b88eae2'
sample_meta = read_csv_uuid(sample_meta_uuid)
in_uuids.append(sample_meta_uuid)

We only need to keep some of the metadata columns that pertain to cohort, subject, and sample. We'll also keep the originating File GUID to help us keep track of provenance. Let's select just these columns:

In [9]:
keep_meta = [
    'cohort.cohortGuid',
    'subject.subjectGuid', 'subject.biologicalSex', 
    'subject.race', 'subject.ethnicity', 'subject.birthYear',
    'sample.sampleKitGuid', 'sample.visitName', 'sample.drawDate',
    'sample.diseaseStatesRecordedAtVisit', 'sample.daysSinceFirstVisit',
    'file.id'
]

In [10]:
sample_meta = sample_meta[keep_meta]

## Read labels and doublet calls from HISE

In [11]:
## search_id values from previous steps
label_search_id = 'zinc-bismuth-bismuth'
doublet_search_id = 'chlorine-sulfur-silver'

search_string = '|'.join([label_search_id, doublet_search_id])

Retrieve files stored in our HISE project store

In [12]:
ps_df = hisepy.list_files_in_project_store('UCSDCU_Y4')
ps_df = ps_df[['id', 'name']]

Filter for files from the previous notebook using our search_id

In [13]:
search_df = ps_df[ps_df['name'].str.contains(search_string)]
search_df = search_df[search_df['name'].str.contains('.parquet')]
search_df = search_df.sort_values('name')

In [14]:
search_df['name'].tolist()

['chlorine-sulfur-silver/ra_scrublet_results_2024-05-10.parquet',
 'zinc-bismuth-bismuth/ra_celltypist_AIFI_L1_2024-05-10.parquet',
 'zinc-bismuth-bismuth/ra_celltypist_AIFI_L2_2024-05-10.parquet',
 'zinc-bismuth-bismuth/ra_celltypist_AIFI_L3_2024-05-10.parquet']

In [15]:
search_df

,id,name
350,5928a13e-8086-49c0-9b8e-df43ca2cfb39,chlorine-sulfur-silver/ra_scrublet_results_202...
352,23abfd47-0d3f-4ca0-88fb-b2b0820f76b1,zinc-bismuth-bismuth/ra_celltypist_AIFI_L1_202...
354,2a6abb94-1628-4307-9abb-69127295ff8a,zinc-bismuth-bismuth/ra_celltypist_AIFI_L2_202...
356,c922d7ba-c596-4f8e-b1df-43bfaeeb0178,zinc-bismuth-bismuth/ra_celltypist_AIFI_L3_202...

## Read and combine label sets to simplify merges

In [17]:
label_list = []
for uuid in search_df['id']:
    res = read_parquet_uuid(uuid)
    res = res.set_index('barcodes', drop = True)
    label_list.append(res)

downloading fileID: 23abfd47-0d3f-4ca0-88fb-b2b0820f76b1
Files have been successfully downloaded!
downloading fileID: 2a6abb94-1628-4307-9abb-69127295ff8a
Files have been successfully downloaded!
downloading fileID: c922d7ba-c596-4f8e-b1df-43bfaeeb0178
Files have been successfully downloaded!

In [18]:
all_labels = pd.concat(label_list, axis = 1)

In [19]:
all_labels = all_labels.reset_index(drop = False)
all_labels.head()

,barcodes,predicted_doublet,doublet_score,AIFI_L1,over_clustering,majority_voting,AIFI_L1_score,AIFI_L2,over_clustering,majority_voting,AIFI_L2_score,AIFI_L3,over_clustering,majority_voting,AIFI_L3_score
0,063d9a88b99611ed84f6d6357bc258e4,False,0.060711,T cell,103,T cell,0.999960,Memory CD4 T cell,103,Memory CD4 T cell,0.856824,CM CD4 T cell,103,CM CD4 T cell,1.0
1,063d9fa6b99611ed84f6d6357bc258e4,False,0.180698,T cell,33,T cell,0.999996,Memory CD4 T cell,33,Memory CD4 T cell,0.946788,CM CD4 T cell,33,CM CD4 T cell,1.0
2,063da5b4b99611ed84f6d6357bc258e4,False,0.043691,Monocyte,39,Monocyte,0.999460,CD14 monocyte,39,CD14 monocyte,0.999232,Core CD14 monocyte,39,Core CD14 monocyte,1.0
3,063dac30b99611ed84f6d6357bc258e4,False,0.013381,T cell,7,T cell,0.999888,Memory CD4 T cell,7,Memory CD4 T cell,0.933583,KLRF1- GZMB+ CD27- memory CD4 T cell,7,KLRF1- GZMB+ CD27- memory CD4 T cell,1.0
4,063dad8eb99611ed84f6d6357bc258e4,False,0.059326,T cell,114,T cell,0.999965,Memory CD4 T cell,114,Memory CD4 T cell,0.954982,CM CD4 T cell,114,CM CD4 T cell,1.0

## Define subsets

In [22]:
subset_column = 'subset_grp'

grps = ["set1", "set2", "set3", "set4"]

num_repeats = len(sample_meta) // len(grps)

assigned_values = np.repeat(grps, num_repeats)

np.random.seed(202405)
np.random.shuffle(assigned_values)

sample_meta.loc[:, subset_column] = assigned_values

In [24]:
subset_counts = sample_meta[subset_column].value_counts()
subset_counts

subset_grp
set2    128
set4    128
set3    128
set1    128
Name: count, dtype: int64

In [26]:
subset_sample_meta = sample_meta.groupby(subset_column)

In [27]:
sample_meta.head()

,cohort.cohortGuid,subject.subjectGuid,subject.biologicalSex,subject.race,subject.ethnicity,subject.birthYear,sample.sampleKitGuid,sample.visitName,sample.drawDate,sample.diseaseStatesRecordedAtVisit,sample.daysSinceFirstVisit,file.id,subset_grp
0,CU1,CU1057,Female,Caucasian,Non-Hispanic origin,1957,KT02989,Flu Year 1 Day 90,2022-01-01T00:00:00Z,Rheumatoid arthritis,120,41caa9d3-12e4-432b-8352-aa012905b823,set2
1,CU1,CU1051,Male,Caucasian,Non-Hispanic origin,1949,KT04080,RA Year 4 Visit 1,2022-08-01T00:00:00Z,Rheumatoid arthritis,460,d5720dff-ea39-4b45-9e45-b7459b779ee6,set4
2,CU1,CU1052,Female,Caucasian,Non-Hispanic origin,1988,KT03932,RA Year 4 Visit 1,2022-08-01T00:00:00Z,Rheumatoid arthritis,458,a2829968-97f2-48c8-bc0a-2989850aebf1,set3
3,CU1,CU1051,Male,Caucasian,Non-Hispanic origin,1949,KT04098,Flu Year 2 Stand-Alone,2022-03-01T00:00:00Z,Rheumatoid arthritis,315,d75a9be9-7092-4915-8532-b75c99a885fe,set4
4,CU1,CU1058,Female,Asian,Non-Hispanic origin,1969,KT04095,RA Year 4 Visit 1,2022-07-01T00:00:00Z,Rheumatoid arthritis,350,6b48b8b3-6848-4f2f-bc63-c2ccd7819948,set3

## Read and assemble anndata objects for each subset

In [28]:
group_input_dict = {}
group_adata_dict = {}
for group, df in subset_sample_meta:
    group_name = group
    #df = df.iloc[0:5] # Remove for full run
    group_uuids = df['file.id'].tolist()
    group_input_dict[group_name] = group_uuids

    # Cache files
    cache_dir = '/home/jupyter/cache'
    cache_paths = []
    for uuid in group_uuids:
        cache_path = '{d}/{u}'.format(d = cache_dir, u = uuid)
        if not os.path.isdir(cache_path):
            hise_res = hisepy.reader.cache_files([uuid])
        cache_paths.append(cache_path)

    # Get cached file paths
    cache_files = []
    for cache_path in cache_paths:
        fn = os.listdir(cache_path)[0]
        cache_files.append('{d}/{f}'.format(d = cache_path, f = fn))

    # Read cached files as anndata
    adata_list = []
    for cache_file in cache_files:
        adata = read_h5_anndata(cache_file)
        adata_list.append(adata)
    group_adata = sc.concat(adata_list)
    
    group_adata_dict[group_name] = group_adata

downloading fileID: 366ef40a-2241-4852-a985-14f9ef616964
Files have been successfully downloaded!
downloading fileID: 6b383ac8-f09b-446b-9366-c71090966909
Files have been successfully downloaded!
downloading fileID: ddbb6500-e453-4ad1-9d0b-874efbbea637
Files have been successfully downloaded!
downloading fileID: 58a68e43-cc40-4b5a-a4b5-5fe9fe73efd1
Files have been successfully downloaded!
downloading fileID: bf43dfa7-ad18-4edd-8eef-1d8740c208fb
Files have been successfully downloaded!
downloading fileID: 64aaa507-69cf-4de4-a0be-1c97e97deffb
Files have been successfully downloaded!
downloading fileID: 5215eda2-0cb0-4008-94f6-9f6ee6d31d71
Files have been successfully downloaded!
downloading fileID: 855aeafb-a170-4365-b055-4c0fdc902379
Files have been successfully downloaded!
downloading fileID: d627d5ad-d847-4e95-8ba6-a6ff2ebe8c16
Files have been successfully downloaded!
downloading fileID: 10c894bd-01e0-4be0-be41-810f45b13eb1
Files have been successfully downloaded!
downloading fileID: 4102a70c-0bea-4444-9a36-ee97164b6538
Files have been successfully downloaded!
downloading fileID: 851e509e-6dfd-4a43-9a2e-994b27983cd3
Files have been successfully downloaded!
downloading fileID: 8dd918fb-4d1a-40ae-b1ee-cf91f5dbe527
Files have been successfully downloaded!
downloading fileID: e57cfa7b-09f8-471c-85cd-5f70dbfa1e4f
Files have been successfully downloaded!
downloading fileID: 61e0caba-7857-4934-8147-6d9f893d76a5
Files have been successfully downloaded!
downloading fileID: f80b691e-20e0-48f0-ac83-3114659bdd9d
Files have been successfully downloaded!
downloading fileID: a3e2f32d-3bbc-4c9a-b3e3-3ee3bbccc63e
Files have been successfully downloaded!
downloading fileID: face5af5-1fa1-458a-8d6f-181ad63f816a
Files have been successfully downloaded!
downloading fileID: cb3e2921-b3ac-4b3f-aec5-47707b866977
Files have been successfully downloaded!
downloading fileID: 4b024c46-d03b-49ac-90fe-d796da57d340
Files have been successfully downloaded!
downloading fileID: 51b53f2f-4fb8-41e9-993d-5060142e994b
Files have been successfully downloaded!
downloading fileID: 81c8776e-935b-48fa-8f13-e34a20863e5b
Files have been successfully downloaded!
downloading fileID: 761f70d2-bdac-4c3d-84fb-a78721172204
Files have been successfully downloaded!
downloading fileID: 9ce7a8a6-5cc7-4af9-bc3d-5f4e77ca16d5
Files have been successfully downloaded!
downloading fileID: b02f374a-fe0e-4e2f-bdaf-99692c8f54e8
Files have been successfully downloaded!
downloading fileID: f9e6c413-6104-4f58-b271-6d93176d5e90
Files have been successfully downloaded!
downloading fileID: 8927001f-bd1e-4346-b4b0-a71a09e9265b
Files have been successfully downloaded!
downloading fileID: df47dbac-808e-43af-ba30-749a6e763134
Files have been successfully downloaded!
downloading fileID: e8d78447-0d81-42f9-a4d6-1f7fcad9ed22
Files have been successfully downloaded!
downloading fileID: 4c725c00-e145-4982-8c7b-2d81556dd776
Files have been successfully downloaded!
downloading fileID: d757772d-e2d8-4061-9957-2589dcde07be
Files have been successfully downloaded!
downloading fileID: 1cbae569-6583-4602-b7b7-53620d0c0b6e
Files have been successfully downloaded!
downloading fileID: 3b75205c-ee1b-46d1-a8a0-7352efbd7a49
Files have been successfully downloaded!
downloading fileID: 7129c71f-5870-4fd1-8b37-4baa34e8bfb6
Files have been successfully downloaded!
downloading fileID: 367fab93-6237-42d4-91d3-65ce4f6565db
Files have been successfully downloaded!
downloading fileID: 79d46e4d-da2a-4d2c-a0ed-c1ab96093513
Files have been successfully downloaded!
downloading fileID: 397db33b-ddf1-4d5b-bd50-a77e03ed2cb3
Files have been successfully downloaded!
downloading fileID: 12a92802-a0dd-4185-a6ee-06b8ecfffbf2
Files have been successfully downloaded!
downloading fileID: 21b4b829-2d16-4b6b-bc6f-d76a37d3aca8
Files have been successfully downloaded!
downloading fileID: f1690b52-e822-4239-a109-ee54e6bbad04
Files have been successfully downloaded!
downloading fileID: 0ceabd5e-57d4-4b48-a0f3-0130457f023f
Files have been successfully downloaded!
downloading fileID: 2f3d7adf-f315-460b-a795-d14681adc50e
Files have been successfully downloaded!
downloading fileID: 084c118f-340f-4b88-bd30-a6dc90e9a66b
Files have been successfully downloaded!
downloading fileID: 972667a4-fa46-4dd7-8063-d54e396b6892
Files have been successfully downloaded!
downloading fileID: 62d75802-46c4-4e10-aece-2258a504c6c8
Files have been successfully downloaded!
downloading fileID: 86717383-b814-4c1d-b58b-a6f3bc5c4ae3
Files have been successfully downloaded!
downloading fileID: 6935e257-61bf-4838-b391-aadbb693df1a
Files have been successfully downloaded!
downloading fileID: ebb43a80-13c5-4255-b772-9fffb4222c1e
Files have been successfully downloaded!
downloading fileID: 458d5770-340c-4750-b7cd-4fada37ed0e0
Files have been successfully downloaded!
downloading fileID: d5865b1f-2278-43ea-bd8a-7ce0450d105b
Files have been successfully downloaded!
downloading fileID: 0bda1472-af7c-47aa-92d4-760c32ed18d0
Files have been successfully downloaded!
downloading fileID: 4e48a56c-efbe-478b-a3f4-0835308cf344
Files have been successfully downloaded!
downloading fileID: de6d9b9c-4bf7-4408-a1c0-3dd66aa38ab6
Files have been successfully downloaded!
downloading fileID: 349c414f-7509-4df4-beb3-e4e73aa068b4
Files have been successfully downloaded!
downloading fileID: a18c4f8a-2d33-4bc9-adee-8c105b54f34a
Files have been successfully downloaded!
downloading fileID: ea466985-009d-4951-87c0-1dcd651ceb94
Files have been successfully downloaded!
downloading fileID: 9c43d40d-198e-41e7-a300-1ec06d12cd0c
Files have been successfully downloaded!
downloading fileID: ec141396-83c6-4ff6-bd32-34041466b35f
Files have been successfully downloaded!
downloading fileID: 2fadf567-27c9-4850-b467-fe4077916330
Files have been successfully downloaded!
downloading fileID: 57aa4381-2729-4b9d-9f6b-ffbe9ae14d58
Files have been successfully downloaded!
downloading fileID: 0eb22b37-7a79-4e5a-8b78-e38e7b9c6f6a
Files have been successfully downloaded!
downloading fileID: 2fd35e47-5c60-4bd5-9b43-fa54b2f4fde3
Files have been successfully downloaded!
downloading fileID: f059f0ec-e8b5-4719-9dda-58886ad31e32
Files have been successfully downloaded!
downloading fileID: d28edbd2-ee3f-4a9f-a0a6-17ad0e8b176a
Files have been successfully downloaded!
downloading fileID: a7165df8-6f62-4fb1-b047-1eef10c3b029
Files have been successfully downloaded!
downloading fileID: de07abec-6c49-4ff0-8dae-8c59df1b4144
Files have been successfully downloaded!
downloading fileID: 568a9fd4-2c67-4302-86a9-051fffe19160
Files have been successfully downloaded!
downloading fileID: 5dd9a323-260c-4689-aebf-0b551ba9a553
Files have been successfully downloaded!
downloading fileID: cde675c9-df12-4f91-8796-e6054764000c
Files have been successfully downloaded!
downloading fileID: fbef56ba-f481-415e-b7b8-ca08c45b5ee2
Files have been successfully downloaded!
downloading fileID: 15e214ab-7230-4df9-beca-fce1c8c51f66
Files have been successfully downloaded!
downloading fileID: b8de3ef6-f1e2-48af-897b-32d4f5725ccb
Files have been successfully downloaded!
downloading fileID: aa03faeb-7493-460c-87f7-0ce08a5b1dc9
Files have been successfully downloaded!
downloading fileID: 9db4b1c9-7347-4adc-8d19-9a13256ab3fb
Files have been successfully downloaded!
downloading fileID: fa52d9c8-1a24-43bb-9735-7bcf79c19436
Files have been successfully downloaded!
downloading fileID: ac28a95d-d7c9-4dfd-b497-edc3137f863f
Files have been successfully downloaded!
downloading fileID: fc0ff57a-5dd8-470b-a6e4-f3441ab7dbaf
Files have been successfully downloaded!
downloading fileID: a0025939-5b52-462a-8b43-e94d4915d385
Files have been successfully downloaded!
downloading fileID: 34d31395-5f5d-48cc-b367-67c69fbca158
Files have been successfully downloaded!
downloading fileID: 6805fec6-c9d4-4cb4-be30-9f44a0f14dae
Files have been successfully downloaded!
downloading fileID: 293cee68-5fc4-4bbb-b6c6-1204b15ed828
Files have been successfully downloaded!
downloading fileID: d3524aa1-079b-4639-90fb-42c90aef975b
Files have been successfully downloaded!
downloading fileID: e9860126-8e53-4db5-b7a3-1157ff59b4b0
Files have been successfully downloaded!
downloading fileID: 27b536f3-9486-430d-9baa-1d85b49ef72f
Files have been successfully downloaded!
downloading fileID: 23392ca3-a83c-49c1-815f-029209bb92a0
Files have been successfully downloaded!
downloading fileID: 56ed77db-020d-4196-b9a0-ef0059af5de2
Files have been successfully downloaded!
downloading fileID: 21f1bbc3-6f1e-4383-bb4b-7f4429dfd28c
Files have been successfully downloaded!
downloading fileID: ec4e55c3-b269-455b-bf5d-e839d2379018
Files have been successfully downloaded!
downloading fileID: dc4b6795-b316-47e5-b0bf-2c0ef769256d
Files have been successfully downloaded!
downloading fileID: abc2bcc8-57ac-4115-8f9c-dac0c6ac5f6f
Files have been successfully downloaded!
downloading fileID: cf7c6d06-5581-4db1-ae81-b8b5a3bf11b4
Files have been successfully downloaded!
downloading fileID: c52ba218-8afe-45a3-9195-ff1c6bc78113
Files have been successfully downloaded!
downloading fileID: afabea47-e6a6-472f-81e0-1b1514dc768a
Files have been successfully downloaded!
downloading fileID: 4e3e9ee0-eb1d-468f-a78a-63c4214db447
Files have been successfully downloaded!
downloading fileID: e4dbe2fc-fc8b-40fe-b546-fcade3ae995c
Files have been successfully downloaded!
downloading fileID: 1703d258-9f00-447f-9f00-4702d5aef553
Files have been successfully downloaded!
downloading fileID: bee488bc-4a87-474c-8532-1dfaa5cfb93d
Files have been successfully downloaded!
downloading fileID: 46f50f2c-7780-4e46-9092-357a6dad5235
Files have been successfully downloaded!
downloading fileID: aa58afa5-d46e-407a-b737-ce9c53b4c568
Files have been successfully downloaded!
downloading fileID: 8aa30541-2766-4c70-9ec9-977a671ec2ef
Files have been successfully downloaded!
downloading fileID: 82ac4092-e1fc-4290-b741-2dd1937c7f73
Files have been successfully downloaded!
downloading fileID: 0a34b5d2-3e09-42ce-80da-0e5b31da0c0a
Files have been successfully downloaded!
downloading fileID: 87855ddf-ae22-43f2-ab49-c88aafc2ec38
Files have been successfully downloaded!
downloading fileID: 0a3c3ce1-2006-4a07-a086-362a1eda303b
Files have been successfully downloaded!
downloading fileID: e49ff1f7-ec03-400a-8fd0-9ea75c03430f
Files have been successfully downloaded!
downloading fileID: 3a00ef7e-60f0-440d-8fc9-44796b6fdb79
Files have been successfully downloaded!
downloading fileID: 360395bc-61ee-4f55-8d9a-9e3a3b8f24bb
Files have been successfully downloaded!
downloading fileID: 70a09944-c8c8-4d47-90e7-15f36037f490
Files have been successfully downloaded!
downloading fileID: fc191b65-f1fd-42b5-95a0-d82519c7cbf7
Files have been successfully downloaded!
downloading fileID: 1312850d-c89e-46b9-a1c1-1c3a8518e7b9
Files have been successfully downloaded!
downloading fileID: 34f7fb29-e412-4f92-8770-55f8e19d40fe
Files have been successfully downloaded!
downloading fileID: b65365e6-5d2e-49d5-8627-e1c5fe45c042
Files have been successfully downloaded!
downloading fileID: aeed82a9-042f-4b6d-8f48-cbc732806502
Files have been successfully downloaded!
downloading fileID: 3c6873c8-b271-46b3-be80-f386b95215af
Files have been successfully downloaded!
downloading fileID: b8c1361e-d945-431f-9678-4484c7fb7335
Files have been successfully downloaded!
downloading fileID: e9740f82-2c03-49cf-bd22-6665ee8d7f42
Files have been successfully downloaded!
downloading fileID: a1cd9778-36cb-4949-aab6-70cde4409892
Files have been successfully downloaded!
downloading fileID: bd5bacfe-0822-43b9-ab79-dad3081351cb
Files have been successfully downloaded!
downloading fileID: dfdd3ba6-892b-490d-8dba-41399dc5cbcc
Files have been successfully downloaded!
downloading fileID: 27851481-5f0c-47d9-8d48-a2ee37eb360c
Files have been successfully downloaded!
downloading fileID: dad81603-3655-40f8-a6c5-9abd1d83dabc
Files have been successfully downloaded!
downloading fileID: 39e6b8d9-dc55-46a9-b0c2-a4b32f7d9f6a
Files have been successfully downloaded!
downloading fileID: 8006e957-aeff-435f-894d-74770b1c5c88
Files have been successfully downloaded!
downloading fileID: 62c51989-bef3-4ef3-9417-a6bed338f930
Files have been successfully downloaded!
downloading fileID: e4bc6b80-aa39-46fc-89f8-c381afd069fc
Files have been successfully downloaded!
downloading fileID: 1c0e2a11-7a7e-4153-9965-d02a9c6546c0
Files have been successfully downloaded!
downloading fileID: fe111261-17b0-4e76-9353-7285a2a5be9b
Files have been successfully downloaded!
downloading fileID: ee66797f-ef97-49df-87e4-853e2cb84f44
Files have been successfully downloaded!
downloading fileID: 41caa9d3-12e4-432b-8352-aa012905b823
Files have been successfully downloaded!
downloading fileID: 3f1aad3d-6ed8-441b-884a-acf2afb47af2
Files have been successfully downloaded!
downloading fileID: 741aff6a-f326-4f82-a8ae-e1e15c8e2b1d
Files have been successfully downloaded!
downloading fileID: 9e281ea0-c0e0-4fb3-9393-1e8dab196faf
Files have been successfully downloaded!
downloading fileID: 8f21518a-25a9-4ddd-856c-59caa1197a82
Files have been successfully downloaded!
downloading fileID: 2a703737-04f7-441c-93ee-b3fcaa9a76d6
Files have been successfully downloaded!
downloading fileID: b0869c09-df3f-4acc-8301-76ace1ea5455
Files have been successfully downloaded!
downloading fileID: 4e73cf8e-f4fd-432b-a5b3-83349905c0f9
Files have been successfully downloaded!
downloading fileID: 2f54e8d2-d663-4927-8789-13d98736666f
Files have been successfully downloaded!
downloading fileID: c64a2c79-a446-4781-8273-a2e4cbf8658d
Files have been successfully downloaded!
downloading fileID: 4446c49c-f182-4b5a-a18e-627d1dde4577
Files have been successfully downloaded!
downloading fileID: 391abb76-b999-43a3-a60b-f7f5f2d2ce39
Files have been successfully downloaded!
downloading fileID: 0ff16338-11c9-4896-a9cd-094b5f68f46b
Files have been successfully downloaded!
downloading fileID: fcf102c7-88b9-43fc-aa75-72e57ca9da58
Files have been successfully downloaded!
downloading fileID: fc56d72b-e398-45e4-952c-0d3b6c620e7d
Files have been successfully downloaded!
downloading fileID: 83a149aa-5025-4f80-a3a0-b88a4fd60be7
Files have been successfully downloaded!
downloading fileID: d9080585-5e41-4047-a7db-011724b52787
Files have been successfully downloaded!
downloading fileID: 019a509f-0f52-44bf-9261-0b1787e1d465
Files have been successfully downloaded!
downloading fileID: 90efed61-4b63-41a2-8541-7b8926f33609
Files have been successfully downloaded!
downloading fileID: b47267c2-2c2b-425a-aba6-d54fdc2a859f
Files have been successfully downloaded!
downloading fileID: 653f73bb-d5f1-40a4-bc5a-b241d90cc26b
Files have been successfully downloaded!
downloading fileID: 618d5f0f-9553-4493-b828-f79504844c93
Files have been successfully downloaded!
downloading fileID: fd419f04-169c-46af-8391-c521f6d096bd
Files have been successfully downloaded!
downloading fileID: 14042fd5-f422-4e3a-bace-aa7cdaa0a34e
Files have been successfully downloaded!
downloading fileID: 15ce48c3-9ec3-4a35-9baf-225979bde0ca
Files have been successfully downloaded!
downloading fileID: bc44f5c2-e728-4b0d-854f-8797af607f30
Files have been successfully downloaded!
downloading fileID: 2b211502-3946-4a74-8f2c-c62b483710af
Files have been successfully downloaded!
downloading fileID: 04cbfe8e-f44f-45cb-8ede-0b092c85397f
Files have been successfully downloaded!
downloading fileID: 24a2b2fa-4b07-4dae-8829-1fb497dc2034
Files have been successfully downloaded!
downloading fileID: a5ba03b5-7a53-4041-90af-61976b3697c9
Files have been successfully downloaded!
downloading fileID: 9d3f9daf-76af-471a-9881-9398aab38293
Files have been successfully downloaded!
downloading fileID: bce1b712-09d4-4fd7-9d31-20c945c9fcf8
Files have been successfully downloaded!
downloading fileID: fccfb5b7-76d5-42c0-af49-8f3b3c0b3ded
Files have been successfully downloaded!
downloading fileID: 8e6e14bb-8e22-4561-bce2-d50e07b63e70
Files have been successfully downloaded!
downloading fileID: 0a7639bf-0589-443e-8a18-798ac96cfc29
Files have been successfully downloaded!
downloading fileID: e49fb6f7-c276-4f8c-bd30-38421282bd04
Files have been successfully downloaded!
downloading fileID: aa471654-f008-4ef4-ad30-d6c9b9b78f23
Files have been successfully downloaded!
downloading fileID: 97948e41-9824-46f5-8e5f-c487f7a66f31
Files have been successfully downloaded!
downloading fileID: d12ce4d0-a353-4cae-9fb2-303dd68f2f8f
Files have been successfully downloaded!
downloading fileID: 2bc869c4-d0b6-44c8-9644-361a2c905d29
Files have been successfully downloaded!
downloading fileID: a35d3e12-8981-49cd-b9ea-e1baa0d3deb6
Files have been successfully downloaded!
downloading fileID: b30698c5-4149-43b7-8ae4-0b52429ca689
Files have been successfully downloaded!
downloading fileID: e164570c-bcfb-43b9-bb21-24b6f2220edc
Files have been successfully downloaded!
downloading fileID: 32e7b936-72af-4cdd-9bc5-2a51d962436d
Files have been successfully downloaded!
downloading fileID: 1bfccdb4-9f3b-4c72-90e1-952a06c536a9
Files have been successfully downloaded!
downloading fileID: 6c81db7f-0c23-40f5-94c2-5a610737527e
Files have been successfully downloaded!
downloading fileID: fc2ae059-042a-4a69-9946-fcec4590be6a
Files have been successfully downloaded!
downloading fileID: 0663733f-9215-420f-8cbf-95f86be1107d
Files have been successfully downloaded!
downloading fileID: 5500cd67-1052-4882-9183-db3278ce9079
Files have been successfully downloaded!
downloading fileID: 5b9a067a-639e-428f-b2b6-508a15414ef5
Files have been successfully downloaded!
downloading fileID: 1e86a172-8a81-467f-a208-692da5ade7a1
Files have been successfully downloaded!
downloading fileID: 60861ad2-7b59-4f2a-9a25-b0b4cbfd959e
Files have been successfully downloaded!
downloading fileID: f75df6e2-cea2-4a71-8321-98871793801c
Files have been successfully downloaded!
downloading fileID: b7240333-1610-4d40-8790-1e6fe50ff8ac
Files have been successfully downloaded!
downloading fileID: 66f52458-2531-4700-a6cd-a08ec80f3849
Files have been successfully downloaded!
downloading fileID: 9dce9d67-baa1-44fc-bd33-0bd5dfa0d3d8
Files have been successfully downloaded!
downloading fileID: c058934a-6b57-4560-8b56-67dac7ef0579
Files have been successfully downloaded!
downloading fileID: bd9d1f04-7009-4c36-a323-0c2e129a823e
Files have been successfully downloaded!
downloading fileID: a6c9e53c-2141-466e-a85d-888de92fbad3
Files have been successfully downloaded!
downloading fileID: c2441884-40f3-4297-abac-ba1bc32d54f3
Files have been successfully downloaded!
downloading fileID: 10052303-e9a3-4e80-83ed-1746beb5a9eb
Files have been successfully downloaded!
downloading fileID: ea04ddcc-9462-46e5-b2b2-184fcde2b8c6
Files have been successfully downloaded!
downloading fileID: 3d76edfb-44fc-4d2d-9e53-9226f2af5a64
Files have been successfully downloaded!
downloading fileID: 758a45dd-5ee4-4e90-b6e4-3b438bcfd4df
Files have been successfully downloaded!
downloading fileID: e897dfd6-d482-4aa6-8a7a-d7ec7a8d7d2d
Files have been successfully downloaded!
downloading fileID: a0081350-3a7e-408a-84bc-e23bbc990f1c
Files have been successfully downloaded!
downloading fileID: e8c336b6-f843-4368-a248-bf913c8ff60b
Files have been successfully downloaded!
downloading fileID: dd6d7a10-c1d3-4cc6-932a-5a937de5952b
Files have been successfully downloaded!
downloading fileID: 07b121f8-e655-4c07-ac75-21aa478364c3
Files have been successfully downloaded!
downloading fileID: b564d367-182a-433f-87aa-86133a0dc835
Files have been successfully downloaded!
downloading fileID: 07c5b451-2fd0-4162-9a14-5be4d7e8f7eb
Files have been successfully downloaded!
downloading fileID: 8910d740-c017-4e2b-bee9-831317cd0356
Files have been successfully downloaded!
downloading fileID: 69706653-3e20-4030-a63a-cc50695cab12
Files have been successfully downloaded!
downloading fileID: 1731f0fb-7799-47a4-9d8a-c85250d61cd5
Files have been successfully downloaded!
downloading fileID: 08dcc4ef-6432-4025-b234-ba6aeb364f50
Files have been successfully downloaded!
downloading fileID: a4e3b63f-60dd-47c9-b861-a655095d76bd
Files have been successfully downloaded!

In [29]:
group_adata_dict.keys()

dict_keys(['set1', 'set2', 'set3', 'set4'])

In [30]:
for group_name, adata in group_adata_dict.items():
    print('{g}: {n} cells'.format(g = group_name, n = adata.shape[0]))

set1: 2087541 cells
set2: 2131497 cells
set3: 2143586 cells
set4: 2157122 cells

In [31]:
sum(adata.shape[0] for adata in group_adata_dict.values())

8519746

## Update Observations with additional metadata

Now, we'll add the sample metadata, CMV status, and BMI data to our scRNA-seq data.

First, we'll convert `pbmc_sample_id` to `sample.sampleKitGuid` using a regular expression. PBMC samples are derived from kits in our LIMS system, so both share the same numerical core. The difference is that there can be multiple PBMC samples collected at the same time, so PBMC samples are prefixed with PB to indicate their sample type, and suffixed with -XX to indicate an aliquot number.

In [32]:
def sample_to_kit(sample):
    kit = re.sub('PB([0-9]+)-.+','KT\\1',sample)
    return(kit)

To keep things tidy, we'll also drop the `seurat_pbmc_type`, `seurat_pbmc_type_score`, and UMAP coordinates generated by our processing pipeline. These cell type assignments are from a now-outdated reference dataset, and the UMAP coordinates are generated for viewing individual samples - not helpful for our full dataset.

In [33]:
drop_columns = [
    'seurat_pbmc_type','seurat_pbmc_type_score',
    'umap_1', 'umap_2'
]

Then, we'll add our new sample data with a left join on the `sample.sampleKitGuid` values, and add our labels and doublet calls with a left join on cell `barcodes`.

Next, we'll convert all of our text columns to categorical. This is used to make storage of text data more efficient when we write our output file, as we'll only need to store a single instance of our strings.

We do this for all columns except barcodes, which we need to retain as a string type for use as an index.

Finally, we'll add these back to our anndata object

In [34]:
for group_name, adata in group_adata_dict.items():
    print('{g}: {p}'.format(g = group_name, p = adata.obs['pbmc_sample_id'].str.startswith('PB').all()))

set1: True
set2: True
set3: True
set4: True

In [35]:
for group_name, adata in group_adata_dict.items():
    print(group_name)
    obs = adata.obs
    
    # Convert sample.sampleKitGuid
    print('converting ids')
    obs['sample.sampleKitGuid'] = [sample_to_kit(sample) for sample in obs['pbmc_sample_id']]
    
    # Drop old columns
    obs = obs.drop(drop_columns, axis = 1)
    
    print('merging sample metadata')
    # Add new metadata
    obs = obs.merge(
        sample_meta,
        how = 'left',
        on = 'sample.sampleKitGuid'
    )
    
    print('merging labels')
    # Add labels
    obs = obs.merge(all_labels, how = 'left', on = 'barcodes')
    
    print('converting to categorical')
    # Convert to categorical
    cat_obs = obs
    for i in range(cat_obs.shape[1]):
        col_name = cat_obs.dtypes.index.tolist()[i]
        col_type = cat_obs.dtypes[col_name]
        if col_name == 'barcodes':
            cat_obs[col_name] = cat_obs[col_name].astype(str)
        elif is_object_dtype(col_type):
            cat_obs[col_name] = cat_obs[col_name].astype('category')
    cat_obs = cat_obs.set_index('barcodes', drop = False)
    
    # Assign final observations back to anndata
    adata.obs = cat_obs
    
    group_adata_dict[group_name] = adata

set1
converting ids
merging sample metadata
merging labels
converting to categorical
set2
converting ids
merging sample metadata
merging labels
converting to categorical
set3
converting ids
merging sample metadata
merging labels
converting to categorical
set4
converting ids
merging sample metadata
merging labels
converting to categorical

## Write assembled data to disk

In [36]:
out_dir = 'output'
if not os.path.isdir(out_dir):
    os.makedirs(out_dir)

In [37]:
out_h5ads = {}
for group_name, adata in group_adata_dict.items():
    out_h5ad = 'output/ra_pbmc_{g}_raw_labeled_{d}.h5ad'.format(g = group_name, d = date.today())
    adata.write_h5ad(out_h5ad)
    out_h5ads[group_name] = out_h5ad

In [39]:
out_csvs = {}
out_parquets = {}
for group_name, adata in group_adata_dict.items():
    obs = adata.obs
    
    out_csv = 'output/ra_pbmc_{g}_raw_labeled_meta_{d}.csv'.format(g = group_name, d = date.today())
    obs.to_csv(out_csv)
    out_csvs[group_name] = out_csv

    out_parquet = 'output/ra_pbmc_{g}_raw_labeled_meta_{d}.parquet'.format(g = group_name, d = date.today())

    obs = obs.loc[:, ~obs.columns.duplicated()] ## remove duplicate columns 
    obs.to_parquet(out_parquet)
    out_parquets[group_name] = out_parquet

## Upload assembled data to HISE

Finally, we'll use `hisepy.upload.upload_files()` to send a copy of our output to HISE to use for downstream analysis steps.

In [40]:
ss = hisepy.get_study_spaces()
print(ss[2]['name'])
print(ss[2]['id'])
study_space_uuid = ss[2]['id']

title = 'Labeled Raw scRNA-seq Assembly {d}'.format(d = date.today())

preRA cross-sectional + earlyRA + Longitudinal analysis
223de760-9624-45bd-aefe-ca24c75b1800

In [41]:
search_id = element_id()
search_id

'radium-uranium-titanium'

In [42]:
in_files = [sample_meta_uuid] + search_df['id'].tolist()
in_files = in_files + sample_meta['file.id'].tolist()

In [43]:
len(in_files)

517

In [44]:
in_files[0:10]

['2b3673ee-827b-415e-837b-f27a0b88eae2',
 '5928a13e-8086-49c0-9b8e-df43ca2cfb39',
 '23abfd47-0d3f-4ca0-88fb-b2b0820f76b1',
 '2a6abb94-1628-4307-9abb-69127295ff8a',
 'c922d7ba-c596-4f8e-b1df-43bfaeeb0178',
 '41caa9d3-12e4-432b-8352-aa012905b823',
 'd5720dff-ea39-4b45-9e45-b7459b779ee6',
 'a2829968-97f2-48c8-bc0a-2989850aebf1',
 'd75a9be9-7092-4915-8532-b75c99a885fe',
 '6b48b8b3-6848-4f2f-bc63-c2ccd7819948']

In [45]:
out_files = list(out_h5ads.values()) + list(out_csvs.values()) + list(out_parquets.values())

In [46]:
out_files

['output/ra_pbmc_set1_raw_labeled_2024-05-10.h5ad',
 'output/ra_pbmc_set2_raw_labeled_2024-05-10.h5ad',
 'output/ra_pbmc_set3_raw_labeled_2024-05-10.h5ad',
 'output/ra_pbmc_set4_raw_labeled_2024-05-10.h5ad',
 'output/ra_pbmc_set1_raw_labeled_meta_2024-05-10.csv',
 'output/ra_pbmc_set2_raw_labeled_meta_2024-05-10.csv',
 'output/ra_pbmc_set3_raw_labeled_meta_2024-05-10.csv',
 'output/ra_pbmc_set4_raw_labeled_meta_2024-05-10.csv',
 'output/ra_pbmc_set1_raw_labeled_meta_2024-05-10.parquet',
 'output/ra_pbmc_set2_raw_labeled_meta_2024-05-10.parquet',
 'output/ra_pbmc_set3_raw_labeled_meta_2024-05-10.parquet',
 'output/ra_pbmc_set4_raw_labeled_meta_2024-05-10.parquet']

In [47]:
hisepy.upload.upload_files(
    files = out_files,
    study_space_id = study_space_uuid,
    title = title,
    input_file_ids = in_files,
    destination = search_id
)

you are trying to upload file_ids... ['output/ra_pbmc_set1_raw_labeled_2024-05-10.h5ad', 'output/ra_pbmc_set2_raw_labeled_2024-05-10.h5ad', 'output/ra_pbmc_set3_raw_labeled_2024-05-10.h5ad', 'output/ra_pbmc_set4_raw_labeled_2024-05-10.h5ad', 'output/ra_pbmc_set1_raw_labeled_meta_2024-05-10.csv', 'output/ra_pbmc_set2_raw_labeled_meta_2024-05-10.csv', 'output/ra_pbmc_set3_raw_labeled_meta_2024-05-10.csv', 'output/ra_pbmc_set4_raw_labeled_meta_2024-05-10.csv', 'output/ra_pbmc_set1_raw_labeled_meta_2024-05-10.parquet', 'output/ra_pbmc_set2_raw_labeled_meta_2024-05-10.parquet', 'output/ra_pbmc_set3_raw_labeled_meta_2024-05-10.parquet', 'output/ra_pbmc_set4_raw_labeled_meta_2024-05-10.parquet']. Do you truly want to proceed?

(y/n) y

{'trace_id': '7d287404-118a-485f-a703-b991c299a517',
 'files': ['output/ra_pbmc_set1_raw_labeled_2024-05-10.h5ad',
  'output/ra_pbmc_set2_raw_labeled_2024-05-10.h5ad',
  'output/ra_pbmc_set3_raw_labeled_2024-05-10.h5ad',
  'output/ra_pbmc_set4_raw_labeled_2024-05-10.h5ad',
  'output/ra_pbmc_set1_raw_labeled_meta_2024-05-10.csv',
  'output/ra_pbmc_set2_raw_labeled_meta_2024-05-10.csv',
  'output/ra_pbmc_set3_raw_labeled_meta_2024-05-10.csv',
  'output/ra_pbmc_set4_raw_labeled_meta_2024-05-10.csv',
  'output/ra_pbmc_set1_raw_labeled_meta_2024-05-10.parquet',
  'output/ra_pbmc_set2_raw_labeled_meta_2024-05-10.parquet',
  'output/ra_pbmc_set3_raw_labeled_meta_2024-05-10.parquet',
  'output/ra_pbmc_set4_raw_labeled_meta_2024-05-10.parquet']}

In [48]:
import session_info
session_info.show()

#### Notes
1. removing majority voting and over clustering columns, rename these 2 columns based on levels?

In [50]:
all_labels.head()

,barcodes,predicted_doublet,doublet_score,AIFI_L1,over_clustering,majority_voting,AIFI_L1_score,AIFI_L2,over_clustering,majority_voting,AIFI_L2_score,AIFI_L3,over_clustering,majority_voting,AIFI_L3_score
0,063d9a88b99611ed84f6d6357bc258e4,False,0.060711,T cell,103,T cell,0.999960,Memory CD4 T cell,103,Memory CD4 T cell,0.856824,CM CD4 T cell,103,CM CD4 T cell,1.0
1,063d9fa6b99611ed84f6d6357bc258e4,False,0.180698,T cell,33,T cell,0.999996,Memory CD4 T cell,33,Memory CD4 T cell,0.946788,CM CD4 T cell,33,CM CD4 T cell,1.0
2,063da5b4b99611ed84f6d6357bc258e4,False,0.043691,Monocyte,39,Monocyte,0.999460,CD14 monocyte,39,CD14 monocyte,0.999232,Core CD14 monocyte,39,Core CD14 monocyte,1.0
3,063dac30b99611ed84f6d6357bc258e4,False,0.013381,T cell,7,T cell,0.999888,Memory CD4 T cell,7,Memory CD4 T cell,0.933583,KLRF1- GZMB+ CD27- memory CD4 T cell,7,KLRF1- GZMB+ CD27- memory CD4 T cell,1.0
4,063dad8eb99611ed84f6d6357bc258e4,False,0.059326,T cell,114,T cell,0.999965,Memory CD4 T cell,114,Memory CD4 T cell,0.954982,CM CD4 T cell,114,CM CD4 T cell,1.0

In [52]:
all_labels.shape

(8519746, 15)